version: '3.4'

services:
  sio.identity:
    image: ${DOCKER_REGISTRY-}sioidentity
    build:
      context: .
      dockerfile: src/SIO.Identity/Dockerfile
    depends_on:
      - sio.identity.sql.identityserver
      - sio.identity.sql
  sio.identity.sql.identityserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
  sio.identity.sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
networks:    
  default:
    external:
        name: sio.network