version: '3.4'

services:
  sio.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Store=Server=sio.sql.store;Initial Catalog=sio-store;User Id=sa;Password=1qaz-pl,
      - ConnectionStrings__IdentityServer=Server=sio.identity.sql.identityserver;Initial Catalog=sio-identityserver;User Id=sa;Password=1qaz-pl,
      - ConnectionStrings__Identity=Server=sio.identity.sql;Initial Catalog=sio-identity;User Id=sa;Password=1qaz-pl,
      - Identity__Authority=https://sio.identity:5001
      - Clients__0__AllowedCorsOrigins__2=https://sio.api:44363
      - Clients__0__AllowedCorsOrigins__3=https://sio.api:42213
      - Clients__1__AllowedCorsOrigins__2=http://sio.front.server:63328
      - Clients__1__AllowedCorsOrigins__3=https://sio.front.server:44348
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sio.identity.sql.identityserver:
    user: 'root'
    environment:
      SA_PASSWORD: "1qaz-pl,"
      ACCEPT_EULA: "Y"
    ports:
      - "1446:1433"
    volumes:
      - /var/opt/mssql/data
  sio.identity.sql:
    user: 'root'
    environment:
      SA_PASSWORD: "1qaz-pl,"
      ACCEPT_EULA: "Y"
    ports:
      - "1447:1433"
    volumes:
      - /var/opt/mssql/data