name: Release

on:
  push:
    branches: [ release/* ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # Restore projects
    - name: Restore projects
      run: dotnet restore

    # Build projects
    - name: Build projects
      run: dotnet build --configuration Release --no-restore

    # Test SIO.Domain.Tests
    - name: Test SIO.Domain.Tests
      run: dotnet test tests/SIO.Domain.Tests/SIO.Domain.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal -- xunit.parallelizeAssembly=true
    # Test SIO.Identity.Tests
    - name: Test SIO.Identity.Tests
      run: dotnet test tests/SIO.Identity.Tests/SIO.Identity.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal -- xunit.parallelizeAssembly=true
    # Test SIO.Infrastructure.Tests
    - name: Test SIO.Infrastructure.Tests
      run: dotnet test tests/SIO.Infrastructure.Tests/SIO.Infrastructure.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal -- xunit.parallelizeAssembly=true
    # Test SIO.Migrations.Tests
    - name: Test SIO.Migrations.Tests
      run: dotnet test tests/SIO.Migrations.Tests/SIO.Migrations.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal -- xunit.parallelizeAssembly=true